package uet.oop.bomberman;

/**
 * Entity types used in game.
 */
public enum BBMType {
    PLAYER, WALL, BRICK, BOMB, FLAME,
    SPEED_ITEM, BOMB_ITEM, FLAME_ITEM,
    PORTAL, BRICK_BREAK, IMMORTAL_ITEM,
    GRASS, CORAL, GRASS_BREAK, CORAL_BREAK,
    BALLOOM_E, ONEAL_E, DORIA_E, WALL_BOMB, GHOST_E,
    AROUND_WALL, DAHL_E, OVAPE_E, PASS_E,
    CHECK_FLAME, ENEMY_DIE
}
